version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-foosball-secret-key-change-in-production}
    restart: unless-stopped
