"""Remove date_played, make start_time required

Revision ID: 452ffef4afe1
Revises: 
Create Date: 2025-10-01 15:32:52.616917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452ffef4afe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, copy date_played values to start_time
    op.execute('UPDATE game SET start_time = date_played WHERE start_time IS NULL')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('date_played')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_played', sa.DATETIME(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # Copy start_time values back to date_played
    op.execute('UPDATE game SET date_played = start_time')

    # ### end Alembic commands ###
