"""Remove date_played, make start_time required

Revision ID: 452ffef4afe1
Revises: 
Create Date: 2025-10-01 15:32:52.616917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452ffef4afe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tables if they don't exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'player' not in inspector.get_table_names():
        op.create_table('player',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )

    if 'game' not in inspector.get_table_names():
        op.create_table('game',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('start_time', sa.DateTime(), nullable=False),
            sa.Column('end_time', sa.DateTime(), nullable=True),
            sa.Column('game_type', sa.String(length=10), nullable=False),
            sa.Column('team1_score', sa.Integer(), nullable=False),
            sa.Column('team2_score', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        # Only do migration if game table already exists with date_played column
        if 'date_played' in [c['name'] for c in inspector.get_columns('game')]:
            # First, copy date_played values to start_time
            op.execute('UPDATE game SET start_time = date_played WHERE start_time IS NULL')

            with op.batch_alter_table('game', schema=None) as batch_op:
                batch_op.alter_column('start_time',
                       existing_type=sa.DATETIME(),
                       nullable=False)
                batch_op.drop_column('date_played')

    if 'game_player' not in inspector.get_table_names():
        op.create_table('game_player',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('game_id', sa.Integer(), nullable=False),
            sa.Column('player_id', sa.Integer(), nullable=False),
            sa.Column('team', sa.Integer(), nullable=False),
            sa.Column('is_winner', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
            sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    if 'cake_balance' not in inspector.get_table_names():
        op.create_table('cake_balance',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('debtor_id', sa.Integer(), nullable=False),
            sa.Column('creditor_id', sa.Integer(), nullable=False),
            sa.Column('balance', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['creditor_id'], ['player.id'], ),
            sa.ForeignKeyConstraint(['debtor_id'], ['player.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_played', sa.DATETIME(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # Copy start_time values back to date_played
    op.execute('UPDATE game SET date_played = start_time')

    # ### end Alembic commands ###
