"""Add elo_rating to Player model

Revision ID: 467ce614a99a
Revises: 452ffef4afe1
Create Date: 2025-10-21 14:20:53.372173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467ce614a99a'
down_revision = '452ffef4afe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo_rating', sa.Integer(), nullable=False, server_default='1500'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('elo_rating')

    # ### end Alembic commands ###
