"""Add GameAuditLog for edit transparency

Revision ID: a1b2c3d4e5f6
Revises: 95dfed98d8cf
Create Date: 2026-02-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '95dfed98d8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.Column('editor_ip', sa.String(length=45), nullable=True),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_audit_log')
    # ### end Alembic commands ###
