"""Add game-type-specific ELO fields to Player model

Revision ID: a1b2c3d4e5f6
Revises: 95dfed98d8cf
Create Date: 2025-11-18 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '95dfed98d8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo_1v1', sa.Integer(), nullable=False, server_default='1500'))
        batch_op.add_column(sa.Column('elo_2v2', sa.Integer(), nullable=False, server_default='1500'))
        batch_op.add_column(sa.Column('elo_2v1', sa.Integer(), nullable=False, server_default='1500'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('elo_2v1')
        batch_op.drop_column('elo_2v2')
        batch_op.drop_column('elo_1v1')

    # ### end Alembic commands ###
