"""Add elo_change to GamePlayer model

Revision ID: cfb12dcc8333
Revises: 467ce614a99a
Create Date: 2025-10-22 13:45:18.368346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb12dcc8333'
down_revision = '467ce614a99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo_change', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_player', schema=None) as batch_op:
        batch_op.drop_column('elo_change')

    # ### end Alembic commands ###
